### ISSUE TITLE
Move to Cython 3.0

### ISSUE THREAD

**Issue by padix-key** [biotite-dev/biotite#490]
Cython released with 3.0 the first full release with some minor language changes that break the compilation of Biotite's Cython modules (https://github.com/biotite-dev/biotite/issues/438#issuecomment-1683032596).

# TODO

- [x] Fix compile errors in Cython modules
- [x] Update Cython version pyproject.toml
- [x] Update Cython version environment.yml
